Repository KappaSigmaMu/kappasigmamu.github.io, pull requests merged in 2021-07, with the labels that each got.

#6 yarn run eject
  babel.config.js
  config/env.js
  config/getHttpsConfig.js
  config/jest/babelTransform.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/modules.js
  config/paths.js
  config/pnpTs.js
  config/webpack.config.js
  config/webpackDevServer.config.js
  jest.config.js
  package.json
  scripts/build.js
  scripts/start.js
  scripts/test.js
  src/react-app-env.d.ts
  yarn.lock
Labels: enhancement

#5 Import the canary component
  .github/workflows/main.yml
  babel.config.js
  config/env.js
  config/getHttpsConfig.js
  config/jest/babelTransform.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/modules.js
  config/paths.js
  config/pnpTs.js
  config/webpack.config.js
  config/webpackDevServer.config.js
  cypress/integration/1-getting-started/navbar.ts
  jest.config.js
  package.json
  public/assets/canary.obj
  scripts/build.js
  scripts/start.js
  scripts/test.js
  src/App.tsx
  src/__tests__/App.test.tsx
  src/__tests__/__snapshots__/App.test.tsx.snap
  src/components/canary/index.tsx
  src/components/navbar/index.tsx
  src/components/navbar/logo.png
  src/index.tsx
  src/pages/App.tsx
  src/pages/Home.tsx
  src/react-app-env.d.ts
  src/styles/index.scss
  src/types.d.ts
  yarn.lock
Labels: bug, enhancement

#9 Create landing page based on wireframe
  .prettierrc
  src/App.tsx
  src/components/BlogCard.tsx
  src/pages/Blog.tsx
  src/pages/CyborgJourney.tsx
  src/pages/Home.tsx
  src/static/canary-component.png
  src/static/gavin-wood.png
  src/static/nav-logo.png
  src/styles/index.scss
Labels: wip
